/*
loader.js
variable 'app' is in global scope - i.e. a property of window.
app is our single global object literal - all other functions and properties of 
the game will be properties of app.
*/
"use strict";

// if app exists use the existing copy
// else create a new empty object literal
var app = app || {};

//ANDROID 18 IMAGES
app.images18 = Object.freeze({
    stance: "images/18Stance.png",
	stanceUp: "images/18StanceUp.png",
	stanceDown: "images/18StanceDown.png",
    slowFly: "images/18SlowFly.png",
    fastFly: "images/18FastFly.png",
	flyUp: "images/18FlyUp.png",
	flyUpUp: "images/18FlyUpUp.png",
	flyUpDown: "images/18FlyUpDown.png",
	flyDownSlow: "images/18FlyDownSlow.png",
	flyDownFast: "images/18FlyDownFast.png",
	reverse: "images/18Reverse.png",
	leftPunch: "images/18LeftPunch.png",
	rightPunch: "images/18RightPunch.png",
	punchPrep: "images/18PunchPrep.png",
	punchPrepAir: "images/18PunchPrepAir.png",
	rightPunchAir: "images/18RightPunchAir.png",
	leftPunchAir: "images/18LeftPunchAir.png",
	hit1: "images/18Hit1.png",
	hit2: "images/18Hit2.png",
	attackE: "images/18Energy.png",
	blastPrep: "images/18BlastPrep.png",
	hardKick: "images/18HardKick.png",
	ground: "images/18Ground.png",
	fallSide: "images/18FallSide.png",
	hardKickPrep: "images/18HardKickPrep.png",
	hardKickSwing: "images/18HardKickSwing.png",
	hardPunch: "images/18HardPunch.png",
	hardPunchAir: "images/18HardPunchAir.png",
	hardPunchAirPrep: "images/18HardPunchAirPrep.png",
	hardPunchAirSwing: "images/18HardPunchAirSwing.png",
	hardPunchPrep: "images/18HardPunchPrep.png",
	hitHard: "images/18HitHard.png",
	injured: "images/18Injured.png",
	kick: "images/18Kick.png",
	kickPrep: "images/18KickPrep.png",
	leftBlast: "images/18LeftBlast.png",
	rightBlast: "images/18RightBlast.png",
	block: "images/18Block.png",
	fallKick: "images/18FallKick.png",
	fallDown: "images/18FallDown.png",
	taunt: "images/18Taunt.png",
	launchPrep: "images/18LaunchPrep.png",
	launchSwing: "images/18LaunchSwing.png",
	launch: "images/18Launch.png",
	finger: "images/18FingerBeam.png",
	blastSky: "images/18BlastSky.png",
	energyDown: "images/18EnergyDown.png",
	energyDown2: "images/18EnergyDown2.png",
	special1: "images/18Special1.png",
	special2: "images/18Special2.png",
	mad1: "images/18Mad1.png",
	field1: "images/18Field1.png",
	field2: "images/18Field2.png",
	combat1: "images/18Combat.png",
	flare: "images/18Flare.png",
	DD1: "images/18DD1.png",
	DD2: "images/18DD2.png",
	
 });
 
 //VEGETA IMAGES
 app.imagesVegeta = Object.freeze({
    stance: "images/VegetaStance.png",
	stanceUp: "images/VegetaStanceUp.png",
	stanceDown: "images/VegetaStanceDown.png",
    slowFly: "images/VegetaSlowFly.png",
    fastFly: "images/VegetaFastFly.png",
	flyUp: "images/VegetaFlyUp.png",
	flyUpUp: "images/VegetaFlyUpUp.png",
	flyUpDown: "images/VegetaFlyUpDown.png",
	flyDownSlow: "images/VegetaFlyDownSlow.png",
	flyDownFast: "images/VegetaFlyDownFast.png",
	reverse: "images/VegetaReverse.png",
	punch: "images/VegetaPunch.png",
	knee: "images/VegetaKnee.png",
	punchPrep: "images/VegetaPunchPrep.png",
	hit1: "images/VegetaHit1.png",
	hardKick: "images/VegetaHardKick.png",
	ground: "images/VegetaGround.png",
	fallSide: "images/VegetaFallSide.png",
	attackE: "images/VegetaEnergy.png",
	hardKickPrep: "images/VegetaHardKickPrep.png",
	hardKickSwing: "images/VegetaHardKickSwing.png",
	hardPunch: "images/VegetaHardPunch.png",
	hardPunchAir: "images/VegetaHardPunchAir.png",
	hardPunchAirPrep: "images/VegetaHardPunchAirPrep.png",
	hardPunchAirSwing: "images/VegetaHardPunchAirSwing.png",
	hardPunchPrep: "images/VegetaHardPunchPrep.png",
	hitHard: "images/VegetaHitHard.png",
	injured: "images/VegetaInjured.png",
	kick: "images/VegetaKick.png",
	kickPrep: "images/VegetaKickPrep.png",
	leftBlast: "images/VegetaLeftBlast.png",
	rightBlast: "images/VegetaRightBlast.png",
	block: "images/VegetaBlock.png",
	fallKick: "images/VegetaFallKick.png",
	fallDown: "images/VegetaFallDown.png",
	taunt: "images/VegetaTaunt.png",
	launchPrep: "images/VegetaLaunchPrep.png",
	launchSwing: "images/VegetaLaunchSwing.png",
	launch: "images/VegetaLaunch.png",
	charge: "images/VegetaCharge.png",
	pose1: "images/VegetaPose1.png",
	pose2: "images/VegetaPose2.png",
	pose3: "images/VegetaPose3.png",
	pose4: "images/VegetaPose4.png",
	special1: "images/VegetaSpecial1.png",
	burst1: "images/VegetaBurst1.png",
	burst2: "images/VegetaBurst2.png",
	struggle1: "images/VegetaStruggle1.png",
 });
 
 //ANDROID 17 IMAGES
 app.images17 = Object.freeze({
    stance: "images/17Stance.png",
	stanceUp: "images/17StanceUp.png",
	stanceDown: "images/17StanceDown.png",
	slowFly: "images/17SlowFly.png",
    fastFly: "images/17FastFly.png",
	flyUp: "images/17FlyUp.png",
	flyUpUp: "images/17FlyUpUp.png",
	flyUpDown: "images/17FlyUpDown.png",
	flyDown: "images/17FlyDown.png",
	reverse: "images/17Reverse.png",
	leftPunch: "images/17LeftPunch.png",
	rightPunch: "images/17RightPunch.png",
	punchPrep: "images/17PunchPrep.png",
	hit1: "images/17Hit1.png",
	fallDown: "images/17FallDown.png",
	fallKick: "images/17FallKick.png",
	fallKick2: "images/17FallKick2.png",
	kick: "images/17Kick.png",
	kickPrep: "images/17KickPrep.png",
	hitHard: "images/17HitHard.png",
	fallSide: "images/17FallSide.png",
	attackE: "images/17Energy.png",
	hardKickPrep: "images/17HardKickPrep.png",
	hardKick: "images/17HardKick.png",
	launch: "images/17Launch.png",
	block: "images/17Block.png",
	blast: "images/17Blast.png",
	drop: "images/17Drop.png",
	finger: "images/17Finger.png",
	ground: "images/17Ground.png",
	injured: "images/17Injured.png",
	injuredUp: "images/17InjuredUp.png",
	injured2: "images/17Injured2.png",
	injuredHit: "images/17InjuredHit.png",
	injuredBlast: "images/17InjuredBlast.png",
	injuredBlast2: "images/17InjuredBlast2.png",
	field1: "images/17Field1.png",
	special1: "images/17Special1.png",
	special2: "images/17Special2.png"
	
 });
 
  //Dr GERO IMAGES
 app.imagesGero = Object.freeze({
    stance: "images/GeroStance.png",
	slowFly: "images/GeroSlowFly.png",
    fastFly: "images/GeroFastFly.png",
	flyUp: "images/GeroFlyUp.png",
	flyDownSlow: "images/GeroFlyDownSlow.png",
	flyDownFast: "images/GeroFlyDownSlow.png",
	reverse: "images/GeroReverse.png",
	leftPunch: "images/GeroLeftPunch.png",
	rightPunch: "images/GeroRightPunch.png",
	punchPrep: "images/GeroPunchPrep.png",
	hit1: "images/GeroHit1.png",
	fallDown: "images/GeroFallDown.png",
	kick: "images/GeroKick.png",
	kickPrep: "images/GeroKickPrep.png",
	hitHard: "images/GeroHitHard.png",
	injured: "images/GeroInjured.png",
	fallSide: "images/GeroFallSide.png",
	geroStill1: "images/GeroStill1.png",
	geroStill2: "images/GeroStill2.png",
	geroStill3: "images/GeroStill3.png",
	geroStill4: "images/GeroStill4.png"
 });
 
 //PICCOLO IMAGES
 app.imagesPiccolo = Object.freeze({ //Piccolo
    stance: "images/PiccoloStance.png",
	stanceUp: "images/PiccoloStanceUp.png",
	stanceDown: "images/PiccoloStanceDown.png",
    slowFly: "images/PiccoloSlowFly.png",
    fastFly: "images/PiccoloFastFly.png",
	flyUp: "images/PiccoloFlyUp.png",
	flyUpUp: "images/PiccoloFlyUpUp.png",
	flyUpDown: "images/PiccoloFlyUpDown.png",
	flyDownSlow: "images/PiccoloFlyDownSlow.png",
	flyDownFast: "images/PiccoloFlyDownFast.png",
	reverse: "images/PiccoloReverse.png",
	punch: "images/PiccoloPunch.png",
	kneePrep: "images/PiccoloKneePrep.png",
	knee: "images/PiccoloKnee.png",
	punchPrep: "images/PiccoloPunchPrep.png",
	hit1: "images/PiccoloHit1.png",
	hit2: "images/PiccoloHit2.png",
	hardKick: "images/PiccoloHardKick.png",
	ground: "images/DeadPiccolo.png",
	fallSide: "images/PiccoloFallSide.png",
	hardKickPrep: "images/PiccoloHardKickPrep.png",
	hardKickSwing: "images/PiccoloHardKickPrep.png",
	hardPunch: "images/PiccoloHardPunch.png",
	hardPunchAir: "images/PiccoloHardPunchAir.png",
	hardPunchAirPrep: "images/PiccoloHardPunchAirPrep.png",
	hardPunchAirSwing: "images/PiccoloHardPunchAirSwing.png",
	hardPunchPrep: "images/PiccoloHardPunchPrep.png",
	fallKick: "images/PiccoloFallKick.png",
	hitHard: "images/PiccoloHitHard.png",
	injured: "images/PiccoloInjured.png",
	kick: "images/PiccoloKick.png",
	kickPrep: "images/PiccoloKickPrep.png",
	blastPrep: "images/PiccoloBlastPrep.png",
	blast: "images/PiccoloBlast.png",
	blastPrepAir: "images/PiccoloBlastPrepAir.png",
	blastAir: "images/PiccoloBlastAir.png",
	block: "images/PiccoloBlock.png",
	fallDown: "images/PiccoloFallDown.png",
	taunt: "images/PiccoloTaunt.png",
	launchPrep: "images/PiccoloLaunchPrep.png",
	launchSwing: "images/PiccoloLaunchSwing.png",
	launch: "images/PiccoloLaunch.png",
	pose1: "images/PiccoloPose1.png",
	pose2: "images/PiccoloPose2.png",
	pose3: "images/PiccoloPose3.png",
	pose4: "images/PiccoloPose4.png",
	energy1: "images/PiccoloEnergy1.png",
	energy2: "images/PiccoloEnergy2.png",
	energy3: "images/PiccoloEnergy3.png",
	energy4: "images/PiccoloEnergy4.png",
	charge: "images/PiccoloCharge.png",
	beamPrep: "images/PiccoloBeamPrep.png",
	beam: "images/PiccoloBeam.png",
	blast2: "images/PiccoloBlast2.png"
 });
 
 
 //GOHAN IMAGES
 app.imagesGohan = Object.freeze({
    stance: "images/GohanStance.png",
	stanceUp: "images/GohanStanceUp.png",
	stanceDown: "images/GohanStanceDown.png",
    slowFly: "images/GohanSlowFly.png",
    fastFly: "images/GohanFastFly.png",
	flyUp: "images/GohanFlyUp.png",
	flyUpUp: "images/GohanFlyUpUp.png",
	flyUpDown: "images/GohanFlyUpDown.png",
	flyDownSlow: "images/GohanFlyDownSlow.png",
	flyDownFast: "images/GohanFlyDownFast.png",
	reverse: "images/GohanReverse.png",
	leftPunch: "images/GohanLeftPunch.png",
	rightPunch: "images/GohanRightPunch.png",
	punchPrep: "images/GohanPunchPrep.png",
	hit1: "images/GohanHit1.png",
	hardKick: "images/GohanHardKick.png",
	ground: "images/GohanGround.png",
	ground2: "images/GohanGround2.png",
	fallSide: "images/GohanFallSide.png",
	fallKick: "images/GohanFallKick.png",
	beamPrep: "images/GohanBeamPrep.png",
	beam: "images/GohanBeam.png",
	beamUp: "images/GohanBeamUp.png",
	beamDown: "images/GohanBeamDown.png",
	hardKickPrep: "images/GohanHardKickPrep.png",
	hardKickSwing: "images/GohanHardKickSwing.png",
	hardPunchAir: "images/GohanHardPunchAir.png",
	hardPunchAirPrep: "images/GohanHardPunchAirPrep.png",
	hardPunchAirSwing: "images/GohanHardPunchAirSwing.png",
	hardPunchPrep: "images/GohanHardPunchPrep.png",
	hardPunchSwing: "images/GohanHardPunchSwing.png",
	hardPunchSwing2: "images/GohanHardPunchSwing2.png",
	hitHard: "images/GohanHitHard.png",
	injured: "images/GohanInjured.png",
	kick: "images/GohanKick.png",
	kickPrep: "images/GohanKickPrep.png",
	blast: "images/GohanBlast.png",
	blastPrep: "images/GohanBlastPrep.png",
	head: "images/GohanHead.png",
	headPrep: "images/GohanHeadPrep.png",
	block: "images/GohanBlock.png",
	fallDown: "images/GohanFallDown.png",
	taunt: "images/GohanTaunt.png",
	launchPrep: "images/GohanLaunchPrep.png",
	launchSwing: "images/GohanLaunchSwing.png",
	launch: "images/GohanLaunch.png",
	charge: "images/GohanCharge.png",
	gohanSevere: "images/GohanSevere.png",
	gohanSevere2: "images/GohanSevere2.png",
	mad1: "images/GohanMad1.png",
	ss2: "images/GohanSS2.png",
	aura1: "images/GohanAura1.png",
	aura2: "images/GohanAura2.png",
	aura3: "images/GohanAura3.png",
	aura4: "images/GohanAura4.png",
	aura5: "images/GohanAura5.png"
 });
 
 
 //TIEN IMAGES
 app.imagesTien = Object.freeze({
    stance: "images/TienStance.png",
	stanceUp: "images/TienStanceUp.png",
	stanceDown: "images/TienStanceDown.png",
    slowFly: "images/TienSlowFly.png",
    fastFly: "images/TienFastFly.png",
	flyUp: "images/TienFlyUp.png",
	flyUpUp: "images/TienFlyUpUp.png",
	flyUpDown: "images/TienFlyUpDown.png",
	flyDownSlow: "images/TienFlyDownSlow.png",
	flyDownFast: "images/TienFlyDownSlow.png",
	reverse: "images/TienReverse.png",
	hit1: "images/TienHit1.png",
	ground: "images/TienGround.png",
	ground2: "images/TienGround2.png",
	fallSide: "images/TienFallSide.png",
	hitHard: "images/TienHitHard.png",
	injured: "images/TienInjured.png",
	fallDown: "images/TienFallDown.png",
	taunt: "images/TienTaunt.png",
	solar: "images/TienSolarFlare.png",
	triBeam1: "images/TienTriBeam1.png",
	triBeam2: "images/TienTriBeam2.png",
	triBeam3: "images/TienTriBeam3.png",
	triBeam4: "images/TienTriBeam4.png",
	triBeam5: "images/TienTriBeam5.png",
	mad1: "images/TienMad1.png"
 });
 
 
 //KRILLIN IMAGES
 app.imagesKrillin = Object.freeze({
    stance: "images/KrillinStance.png",
	stanceUp: "images/KrillinStanceUp.png",
	stanceDown: "images/KrillinStanceDown.png",
    slowFly: "images/KrillinSlowFly.png",
    fastFly: "images/KrillinFastFly.png",
	flyUp: "images/KrillinFlyUp.png",
	flyUpUp: "images/KrillinFlyUpUp.png",
	flyUpDown: "images/KrillinFlyUpDown.png",
	flyDownSlow: "images/KrillinFlyDownSlow.png",
	flyDownFast: "images/KrillinFlyDownSlow.png",
	reverse: "images/KrillinReverse.png",
	hit1: "images/KrillinHit1.png",
	ground: "images/KrillinGround.png",
	ground2: "images/KrillinGround2.png",
	fallSide: "images/KrillinFallSide.png",
	hitHard: "images/KrillinHitHard.png",
	injured: "images/KrillinInjured.png",
	fallDown: "images/KrillinFallDown.png",
	taunt: "images/KrillinTaunt.png",
	solar: "images/KrillinSolarFlare.png",
	disk1: "images/KrillinDisk1.png",
	disk2: "images/KrillinDisk2.png",
	disk3: "images/KrillinDisk3.png",
	disk4: "images/KrillinDisk4.png",
	mad1: "images/KrillinMad1.png",
	mad2: "images/KrillinMad2.png",
 });
 
app.images16 = Object.freeze({
    stance: "images/16Stance.png",
	stance2: "images/16Stance2.png"
 }); 
 
 
 //STAGE AND ENVIRONMENT IMAGES
 app.environment = Object.freeze({
    city: "images/cityBackground3.png",
	cityTop: "images/cityBackgroundTop.png",
	cityDamage1: "images/cityBackground5.png",
	cityForeground1: "images/cityForeground1.png",
	cityForeground2: "images/cityForeground2.png",
	titleBar: "images/TitleBar.png",
	digitalBackground: "images/DigitalBackground.png",
	deadPiccolo: "images/DeadPiccolo.png",
	deadPiccolo2: "images/DeadPiccolo2.png",
	deadVegeta2: "images/VegetaGround2.png",
	deadVegeta3: "images/VegetaGround3.png",
	deadVegeta4: "images/VegetaGround4.png",
	building1: "images/building.png",
	lab1: "images/LabStage.png",
	remote2: "images/Remote2.png",
	a19Head: "images/19Head1.png",
	smoke1: "images/Smoke1.png",
	smoke2: "images/smoke2.png",
	smoke3: "images/Smoke3.png",
	cape1: "images/PiccoloCape1.png",
	cape2: "images/PiccoloCape2.png",
	cape3: "images/PiccoloCape3.png",
	cape4: "images/PiccoloCape4.png",
	yamcha1: "images/YamchaStance.png",
	yamcha2: "images/YamchaTaunt.png",
	yamcha3: "images/YamchaArm1.png",
	yamcha4: "images/YamchaArm2.png",
	yamcha5: "images/YamchaFly.png",
	chaotzu1: "images/ChaotzuStance.png",
	chaotzu2: "images/ChaotzuTaunt.png",
	chaotzu3: "images/ChaotzuHat.png",
	chaotzu4: "images/ChaotzuFly.png",
	yajirobe1: "images/Yajirobe1.png",
	groundDustA1: "images/GroundDustA1.png",
	groundDustA2: "images/GroundDustA2.png",
	groundDustA3: "images/GroundDustA3.png",
	groundDustA4: "images/GroundDustA4.png",
	groundDustB1: "images/GroundDustB1.png",
	groundDustB2: "images/GroundDustB2.png",
	groundDustB3: "images/GroundDustB3.png",
	groundDustB4: "images/GroundDustB4.png",
	groundDustC1: "images/GroundDustC1.png",
	groundDustC2: "images/GroundDustC2.png",
	groundDustC3: "images/GroundDustC3.png",
	groundDustC4: "images/GroundDustC4.png",
	gerosSpy1: "images/GerosSpy1.png",
	smog1: "images/smog1.png",
	smog2: "images/smog2.png",
	smog3: "images/smog3.png",
	smog4: "images/smog4.png",
	smog5: "images/smog5.png",
	smog6: "images/smog6.png",
	smog7: "images/smog7.png",
	smog8: "images/smog8.png",
	smog9: "images/smog9.png",
	smog10: "images/smog10.png",
	smog11: "images/smog11.png",
	smog12: "images/smog12.png",
	smog13: "images/smog13.png",
	smog14: "images/smog14.png",
	smog15: "images/smog15.png",
	smog16: "images/smog16.png",
	detect1: "images/Detect1.png",
	clash1: "images/clash1.png",
	clash2: "images/clash2.png",
	clash3: "images/clash3.png",
 });
 
 //UI IMAGES
  app.gameUI = Object.freeze({
    iBorder: "images/InterfaceBorder.png",
	iBackground: "images/InterfaceBackground.png",
	iBackground130: "images/InterfaceBackground130.png",
	iBackground140: "images/InterfaceBackground140.png",
	iBackground160: "images/InterfaceBackground160.png",
	iBigBar: "images/InterfaceBigBar.png",
	iBigBar2: "images/InterfaceBigBar2.png",
	iSmallBar: "images/InterfaceSmallBar.png",
	redRibbon: "images/RedRibbon.png",
	redRibbonRust: "images/RedRibbonRust.png",
	redRibbonBronze: "images/RedRibbonBronze.png",
	redRibbonSilver: "images/RedRibbonSilver.png",
	redRibbonGold: "images/RedRibbonGold.png",
	warning: "images/WarningImage.png"
 });
 
 //ATTACK IMAGES
 app.attack = Object.freeze({
	 tele: "images/Tele.png",
	 tele2: "images/Tele2.png",
	 tele3: "images/Tele3.png",
	 tele4: "images/Tele4.png",
	 tele5: "images/Tele5.png",
	 tele6: "images/Tele6.png",
	 teleThin: "images/TeleThin.png",
	 tele2Thin: "images/Tele2Thin.png",
	 tele3Thin: "images/Tele3Thin.png",
	 tele4Thin: "images/Tele4Thin.png",
	 blast1: "images/blast1.png",
	 explosion1: "images/explosion1.png",
	 explosion2: "images/explosion2.png",
	 explosion3: "images/explosion3.png",
	 explosion4: "images/explosion4.png",
	 explosion5: "images/explosion5.png",
	 explosion6: "images/explosion6.png",
	 bigExplosion1: "images/BigExplosion1.png",
	 bigExplosion2: "images/BigExplosion2.png",
	 bigExplosion3: "images/BigExplosion3.png",
	 bigExplosion4: "images/BigExplosion4.png",
	 bigExplosion5: "images/BigExplosion5.png",
	 bigExplosion6: "images/BigExplosion6.png",
	 circleExplosion2: "images/CircleExplosion2.png",
	 circleExplosion3: "images/CircleExplosion3.png",
	 circleExplosion4: "images/CircleExplosion4.png",
	 circleExplosion5: "images/CircleExplosion5.png",
	 circleExplosion6: "images/CircleExplosion6.png",
	 circleExplosionB2: "images/CircleExplosionB2.png",
	 circleExplosionB3: "images/CircleExplosionB3.png",
	 circleExplosionB4: "images/CircleExplosionB4.png",
	 circleExplosionB5: "images/CircleExplosionB5.png",
	 circleExplosionB6: "images/CircleExplosionB6.png",
	 auraWhite1: "images/AuraWhite1.png",
	 auraWhite2: "images/AuraWhite2.png",
	 auraWhite3: "images/AuraWhite3.png",
	 auraWhite4: "images/AuraWhite4.png",
	 auraYellow1: "images/AuraYellow1.png",
	 auraYellow2: "images/AuraYellow2.png",
	 auraYellow3: "images/AuraYellow3.png",
	 auraYellow4: "images/AuraYellow4.png",
	 beam1: "images/Beam1.png",
	 beam2: "images/Beam2.png",
	 beam3: "images/Beam3.png",
	 beam4: "images/Beam4.png",
	 beam5: "images/Beam5.png",
	 ball1: "images/Ball1.png",
	 ball2: "images/Ball2.png",
	 beamB1: "images/BeamBlast1.png",
	 beamB2: "images/BeamBlast2.png",
	 beamB3: "images/BeamBlast3.png",
	 beamB4: "images/BeamBlast4.png",
	 beamB5: "images/BeamBlast5.png",
	 blastCharge1: "images/blastCharge1.png",
	 beamT1: "images/BeamTail1.png",
	 triBeam: "images/TriBeam.png",
	 disk1: "images/Disk1.png",
	 disk2: "images/Disk1.png",
	 sparks1: "images/sparks1.png",
	 sparks2: "images/sparks2.png",
	 sparks3: "images/sparks3.png",
	 sparks4: "images/sparks4.png",
	 burst1: "images/Burst1.png",
	 burst2: "images/Burst2.png",
	 burst3: "images/Burst3.png",
	 burst4: "images/Burst4.png",
	 field1: "images/Field1.png",
	 field2: "images/Field2.png",
	 field3: "images/Field3.png",
	 field4: "images/Field4.png",
	 field5: "images/Field5.png",
	 field6: "images/Field6.png",
	 field7: "images/Field7.png",
	 field8: "images/Field8.png",
	 fieldMain: "images/FieldMain.png",
	 nuke1: "images/nuke1.png",
	 nuke2: "images/nuke2.png",
	 nuke3: "images/nuke3.png",
	 nuke4: "images/nuke4.png",
	 nuke5: "images/nuke5.png",
	 nuke6: "images/nuke6.png",
	 PB1: "images/PB1.png",
	 PB2: "images/PB2.png",
	 PB3: "images/PB3.png",
	 PB4: "images/PB4.png",
	 PB5: "images/PB5.png",
	 PB6: "images/PB6.png",
	 PBC1: "images/PBC1.png",
	 PBC2: "images/PBC2.png",
	 PBC3: "images/PBC3.png",
	 PBC4: "images/PBC4.png",
	 PBC5: "images/PBC5.png",
	 PBC6: "images/PBC6.png",
	 
 });

window.onblur = function(){
	//console.log("blur at " + Date());
	app.main.downsized = true;
	if(app.main.loaded == true && paused == false){
		app.main.pausedGame();
		paused = true;
	}
	if(paused == true){
		app.main.sound.pauseBGAudioPause();
		app.main.sound.pauseBackground();
	}
};

window.onfocus = function(){
	//console.log("focus at " + Date());
	app.main.downsized = false;
	app.main.sound.playBGAudioPause();
	
	if(app.main.onScreen == true && (app.main.gameState == app.main.GAME_STATE.BEGIN || app.main.introState == true || app.main.endingState == true || app.main.specialScene == true) && upVidPlay == false){
		app.main.resumeGame();
	}
}

window.onload = function(){
	//console.log("window.onload called");
	app.main.loaded = false;
	// Preload Images and Sound
	app.main.preInit();
	loadStatssFromServer();
	app.queue = new createjs.LoadQueue(false);
	app.queue.installPlugin(createjs.Sound);
	app.queue.on("complete", function(e){
		//app.main.loaded = true;
		//console.log("images and sounds loaded!");
		/* if(app.main.version != 1){
			modsButton.className = "";
		} */
		modsButton.className = "";
		passwordButton.className = "";
		statsButton.className = "";
		scoreButton.className = "";
		app.sound.init();
		app.main.sound = app.sound;
		app.main.init();
		document.querySelector("#gameButton").click();
	});
	
	app.queue.loadManifest([
	//Environment LOADING
	 {id: "background", src:app.environment.city},
	 {id: "backgroundTop", src:app.environment.cityTop},
	 {id: "foreground1", src:app.environment.cityForeground1},
	 {id: "foreground2", src:app.environment.cityForeground2},
	 {id: "cityDamage1", src:app.environment.cityDamage1},
	 {id: "titleBar", src:app.environment.titleBar},
	 {id: "digitalBackground", src:app.environment.digitalBackground},
	 {id: "deadPiccolo", src:app.environment.deadPiccolo},
	 {id: "deadPiccolo2", src:app.environment.deadPiccolo2},
	 {id: "deadVegeta2", src:app.environment.deadVegeta2},
	 {id: "deadVegeta3", src:app.environment.deadVegeta3},
	 {id: "deadVegeta4", src:app.environment.deadVegeta4},
	 {id: "building1", src:app.environment.building1},
	 {id: "lab1", src:app.environment.lab1},
	 {id: "remote2", src:app.environment.remote2},
	 {id: "a19Head", src:app.environment.a19Head},
	 {id: "smoke1", src:app.environment.smoke1},
	 {id: "smoke2", src:app.environment.smoke2},
	 {id: "smoke3", src:app.environment.smoke3},
	 {id: "cape1", src:app.environment.cape1},
	 {id: "cape2", src:app.environment.cape2},
	 {id: "cape3", src:app.environment.cape3},
	 {id: "cape4", src:app.environment.cape4},
	 {id: "yamcha1", src:app.environment.yamcha1},
	 {id: "yamcha2", src:app.environment.yamcha2},
	 {id: "yamcha3", src:app.environment.yamcha3},
	 {id: "yamcha4", src:app.environment.yamcha4},
	 {id: "yamcha5", src:app.environment.yamcha5},
	 {id: "chaotzu1", src:app.environment.chaotzu1},
	 {id: "chaotzu2", src:app.environment.chaotzu2},
	 {id: "chaotzu3", src:app.environment.chaotzu3},
	 {id: "chaotzu4", src:app.environment.chaotzu4},
	 {id: "yajirobe1", src:app.environment.yajirobe1},
	 {id: "groundDustA1", src:app.environment.groundDustA1},
	 {id: "groundDustA2", src:app.environment.groundDustA2},
	 {id: "groundDustA3", src:app.environment.groundDustA3},
	 {id: "groundDustA4", src:app.environment.groundDustA4},
	 {id: "groundDustB1", src:app.environment.groundDustB1},
	 {id: "groundDustB2", src:app.environment.groundDustB2},
	 {id: "groundDustB3", src:app.environment.groundDustB3},
	 {id: "groundDustB4", src:app.environment.groundDustB4},
	 {id: "groundDustC1", src:app.environment.groundDustC1},
	 {id: "groundDustC2", src:app.environment.groundDustC2},
	 {id: "groundDustC3", src:app.environment.groundDustC3},
	 {id: "groundDustC4", src:app.environment.groundDustC4},
	 {id: "gerosSpy1", src:app.environment.gerosSpy1},
	 {id: "smog1", src:app.environment.smog1},
	 {id: "smog2", src:app.environment.smog2},
	 {id: "smog3", src:app.environment.smog3},
	 {id: "smog4", src:app.environment.smog4},
	 {id: "smog5", src:app.environment.smog5},
	 {id: "smog6", src:app.environment.smog6},
	 {id: "smog7", src:app.environment.smog7},
	 {id: "smog8", src:app.environment.smog8},
	 {id: "smog9", src:app.environment.smog9},
	 {id: "smog10", src:app.environment.smog10},
	 {id: "smog11", src:app.environment.smog11},
	 {id: "smog12", src:app.environment.smog12},
	 {id: "smog13", src:app.environment.smog13},
	 {id: "smog14", src:app.environment.smog14},
	 {id: "smog15", src:app.environment.smog15},
	 {id: "smog16", src:app.environment.smog16},
	 {id: "detect1", src:app.environment.detect1},
	 {id: "clash1", src:app.environment.clash1},
	 {id: "clash2", src:app.environment.clash2},
	 {id: "clash3", src:app.environment.clash3},
	 
	
	 //Interface LOADING
	 {id: "iBorder", src:app.gameUI.iBorder},
     {id: "iBackground", src:app.gameUI.iBackground},
	 {id: "iBackground130", src:app.gameUI.iBackground130},
	 {id: "iBackground140", src:app.gameUI.iBackground140},
	 {id: "iBackground160", src:app.gameUI.iBackground160},
     {id: "iBigBar", src:app.gameUI.iBigBar},
	 {id: "iBigBar2", src:app.gameUI.iBigBar2},
	 {id: "iSmallBar", src:app.gameUI.iSmallBar},
	 {id: "redRibbon", src:app.gameUI.redRibbon},
	 {id: "redRibbonRust", src:app.gameUI.redRibbonRust},
	 {id: "redRibbonBronze", src:app.gameUI.redRibbonBronze},
	 {id: "redRibbonSilver", src:app.gameUI.redRibbonSilver},
	 {id: "redRibbonGold", src:app.gameUI.redRibbonGold},
	 {id: "warning", src:app.gameUI.warning},
	 
	 //Android 18 LOADING
     {id: "18Stance", src:app.images18.stance},
	 {id: "18StanceUp", src:app.images18.stanceUp},
	 {id: "18StanceDown", src:app.images18.stanceDown},
     {id: "18SlowFly", src:app.images18.slowFly},
     {id: "18FastFly", src:app.images18.fastFly},
	 {id: "18FlyUp", src:app.images18.flyUp},
	 {id: "18FlyUpUp", src:app.images18.flyUpUp},
	 {id: "18FlyUpDown", src:app.images18.flyUpDown},
	 {id: "18FlyDownSlow", src:app.images18.flyDownSlow},
	 {id: "18FlyDownFast", src:app.images18.flyDownFast},
	 {id: "18Reverse", src:app.images18.reverse},
	 {id: "18LeftPunch", src:app.images18.leftPunch},
	 {id: "18RightPunch", src:app.images18.rightPunch},
	 {id: "18PunchPrep", src:app.images18.punchPrep},
	 {id: "18PunchPrepAir", src:app.images18.punchPrepAir},
	 {id: "18RightPunchAir", src:app.images18.rightPunchAir},
	 {id: "18LeftPunchAir", src:app.images18.leftPunchAir},
	 {id: "18Hit1", src:app.images18.hit1},
	 {id: "18Hit2", src:app.images18.hit2},
	 {id: "18AttackE", src:app.images18.attackE},
	 {id: "18BlastPrep", src:app.images18.blastPrep},
	 {id: "18HardKick", src:app.images18.hardKick},
	 {id: "18Ground", src:app.images18.ground},
	 {id: "18FallSide", src:app.images18.fallSide},
	 {id: "18HardKickPrep", src:app.images18.hardKickPrep},
	 {id: "18HardKickSwing", src:app.images18.hardKickSwing},
	 {id: "18HardPunch", src:app.images18.hardPunch},
	 {id: "18HardPunchAir", src:app.images18.hardPunchAir},
	 {id: "18HardPunchAirPrep", src:app.images18.hardPunchAirPrep},
	 {id: "18HardPunchAirSwing", src:app.images18.hardPunchAirSwing},
	 {id: "18HardPunchPrep", src:app.images18.hardPunchPrep},
	 {id: "18HitHard", src:app.images18.hitHard},
	 {id: "18Injured", src:app.images18.injured},
	 {id: "18Kick", src:app.images18.kick},
	 {id: "18KickPrep", src:app.images18.kickPrep},
	 {id: "18LeftBlast", src:app.images18.leftBlast},
	 {id: "18RightBlast", src:app.images18.rightBlast},
	 {id: "18Block", src:app.images18.block},
	 {id: "18FallKick", src:app.images18.fallKick},
	 {id: "18FallDown", src:app.images18.fallDown},
	 {id: "18Taunt", src:app.images18.taunt},
	 {id: "18launchPrep", src:app.images18.launchPrep},
	 {id: "18launchSwing", src:app.images18.launchSwing},
	 {id: "18launch", src:app.images18.launch},
	 {id: "18finger", src:app.images18.finger},
	 {id: "18BlastSky", src:app.images18.blastSky},
	 {id: "18EnergyDown", src:app.images18.energyDown},
	 {id: "18EnergyDown2", src:app.images18.energyDown2},
	 {id: "18Special1", src:app.images18.special1},
	 {id: "18Special2", src:app.images18.special2},
	 {id: "18Mad1", src:app.images18.mad1},
	 {id: "18Field1", src:app.images18.field1},
	 {id: "18Field2", src:app.images18.field2},
	 {id: "18Combat1", src:app.images18.combat1},
	 {id: "18Flare", src:app.images18.flare},
	 {id: "18DD1", src:app.images18.DD1},
	 {id: "18DD2", src:app.images18.DD2},
	 
	 //Vegeta LOADING
	 {id: "vegetaStance", src:app.imagesVegeta.stance},
	 {id: "vegetaStanceUp", src:app.imagesVegeta.stanceUp},
	 {id: "vegetaStanceDown", src:app.imagesVegeta.stanceDown},
	 {id: "vegetaHit1", src:app.imagesVegeta.hit1},
	 {id: "vegetaAttackE", src:app.imagesVegeta.attackE},
     {id: "vegetaSlowFly", src:app.imagesVegeta.slowFly},
     {id: "vegetaFastFly", src:app.imagesVegeta.fastFly},
	 {id: "vegetaFlyUp", src:app.imagesVegeta.flyUp},
	 {id: "vegetaFlyUpUp", src:app.imagesVegeta.flyUpUp},
	 {id: "vegetaFlyUpDown", src:app.imagesVegeta.flyUpDown},
	 {id: "vegetaFlyDownSlow", src:app.imagesVegeta.flyDownSlow},
	 {id: "vegetaFlyDownFast", src:app.imagesVegeta.flyDownFast},
	 {id: "vegetaReverse", src:app.imagesVegeta.reverse},
	 {id: "vegetaPunch", src:app.imagesVegeta.punch},
	 {id: "vegetaKnee", src:app.imagesVegeta.knee},
	 {id: "vegetaPunchPrep", src:app.imagesVegeta.punchPrep},
	 {id: "vegetaHardKick", src:app.imagesVegeta.hardKick},
	 {id: "vegetaGround", src:app.imagesVegeta.ground},
	 {id: "vegetaFallSide", src:app.imagesVegeta.fallSide},
	 {id: "vegetaHardKickPrep", src:app.imagesVegeta.hardKickPrep},
	 {id: "vegetaHardKickSwing", src:app.imagesVegeta.hardKickSwing},
	 {id: "vegetaHardPunch", src:app.imagesVegeta.hardPunch},
	 {id: "vegetaHardPunchAir", src:app.imagesVegeta.hardPunchAir},
	 {id: "vegetaHardPunchAirPrep", src:app.imagesVegeta.hardPunchAirPrep},
	 {id: "vegetaHardPunchAirSwing", src:app.imagesVegeta.hardPunchAirSwing},
	 {id: "vegetaHardPunchPrep", src:app.imagesVegeta.hardPunchPrep},
	 {id: "vegetaHitHard", src:app.imagesVegeta.hitHard},
	 {id: "vegetaInjured", src:app.imagesVegeta.injured},
	 {id: "vegetaKick", src:app.imagesVegeta.kick},
	 {id: "vegetaKickPrep", src:app.imagesVegeta.kickPrep},
	 {id: "vegetaLeftBlast", src:app.imagesVegeta.leftBlast},
	 {id: "vegetaRightBlast", src:app.imagesVegeta.rightBlast},
	 {id: "vegetaBlock", src:app.imagesVegeta.block},
	 {id: "vegetaFallKick", src:app.imagesVegeta.fallKick},
	 {id: "vegetaFallDown", src:app.imagesVegeta.fallDown},
	 {id: "vegetaTaunt", src:app.imagesVegeta.taunt},
	 {id: "vegetalaunchPrep", src:app.imagesVegeta.launchPrep},
	 {id: "vegetalaunchSwing", src:app.imagesVegeta.launchSwing},
	 {id: "vegetalaunch", src:app.imagesVegeta.launch},
	 {id: "vegetaCharge", src:app.imagesVegeta.charge},
	 {id: "vegetaPose1", src:app.imagesVegeta.pose1},
	 {id: "vegetaPose2", src:app.imagesVegeta.pose2},
	 {id: "vegetaPose3", src:app.imagesVegeta.pose3},
	 {id: "vegetaPose4", src:app.imagesVegeta.pose4},
	 {id: "vegetaSpecial1", src:app.imagesVegeta.special1},
	 {id: "vegetaBurst1", src:app.imagesVegeta.burst1},
	 {id: "vegetaBurst2", src:app.imagesVegeta.burst2},
	 {id: "vegetaStruggle1", src:app.imagesVegeta.struggle1},
	 
	 //Android 17 LOADING
	 {id: "17Stance", src:app.images17.stance},
	 {id: "17StanceUp", src:app.images17.stanceUp},
	 {id: "17StanceDown", src:app.images17.stanceDown},
	 {id: "17Hit1", src:app.images17.hit1},
     {id: "17SlowFly", src:app.images17.slowFly},
     {id: "17FastFly", src:app.images17.fastFly},
	 {id: "17FlyUp", src:app.images17.flyUp},
	 {id: "17FlyUpUp", src:app.images17.flyUpUp},
	 {id: "17FlyUpDown", src:app.images17.flyUpDown},
	 {id: "17FlyDown", src:app.images17.flyDown},
	 {id: "17Reverse", src:app.images17.reverse},
	 {id: "17Kick", src:app.images17.kick},
	 {id: "17KickPrep", src:app.images17.kickPrep},
	 {id: "17LeftPunch", src:app.images17.leftPunch},
	 {id: "17RightPunch", src:app.images17.rightPunch},
	 {id: "17PunchPrep", src:app.images17.punchPrep},
	 {id: "17FallSide", src:app.images17.fallSide},
	 {id: "17FallDown", src:app.images17.fallDown},
	 {id: "17FallKick", src:app.images17.fallKick},
	 {id: "17FallKick2", src:app.images17.fallKick2},
	 {id: "17HitHard", src:app.images17.hitHard},
	 {id: "17Launch", src:app.images17.launch},
	 {id: "17AttackE", src:app.images17.attackE},
	 {id: "17Blast", src:app.images17.blast},
	 {id: "17HardKick", src:app.images17.hardKick},
	 {id: "17HardKickPrep", src:app.images17.hardKick},
	 {id: "17Block", src:app.images17.block},
	 {id: "17Drop", src:app.images17.drop},
	 {id: "17Finger", src:app.images17.finger},
	 {id: "17Ground", src:app.images17.ground},
	 {id: "17Injured", src:app.images17.injured},
	 {id: "17InjuredUp", src:app.images17.injuredUp},
	 {id: "17Injured2", src:app.images17.injured2},
	 {id: "17InjuredHit", src:app.images17.injuredHit},
	 {id: "17InjuredBlast", src:app.images17.injuredBlast},
	 {id: "17InjuredBlast2", src:app.images17.injuredBlast2},
	 {id: "17Field1", src:app.images17.field1},
	 {id: "17Special1", src:app.images17.special1},
	 {id: "17Special2", src:app.images17.special2},
	 
	 
	 //Dr Gero LOADING
	 {id: "geroStance", src:app.imagesGero.stance},
	 {id: "geroHit1", src:app.imagesGero.hit1},
     {id: "geroSlowFly", src:app.imagesGero.slowFly},
     {id: "geroFastFly", src:app.imagesGero.fastFly},
	 {id: "geroFlyUp", src:app.imagesGero.flyUp},
	 {id: "geroFlyDownSlow", src:app.imagesGero.flyDownSlow},
	 {id: "geroFlyDownFast", src:app.imagesGero.flyDownFast},
	 {id: "geroReverse", src:app.imagesGero.reverse},
	 {id: "geroKick", src:app.imagesGero.kick},
	 {id: "geroKickPrep", src:app.imagesGero.kickPrep},
	 {id: "geroLeftPunch", src:app.imagesGero.leftPunch},
	 {id: "geroRightPunch", src:app.imagesGero.rightPunch},
	 {id: "geroPunchPrep", src:app.imagesGero.punchPrep},
	 {id: "geroFallSide", src:app.imagesGero.fallSide},
	 {id: "geroFallDown", src:app.imagesGero.fallDown},
	 {id: "geroInjured", src:app.imagesGero.injured},
	 {id: "geroHitHard", src:app.imagesGero.hitHard},
	 {id: "geroStill1", src:app.imagesGero.geroStill1},
	 {id: "geroStill2", src:app.imagesGero.geroStill2},
	 {id: "geroStill3", src:app.imagesGero.geroStill3},
	 {id: "geroStill4", src:app.imagesGero.geroStill4},
	 
	 
	 //Piccolo LOADING
	 {id: "piccoloStance", src:app.imagesPiccolo.stance},
	 {id: "piccoloStanceUp", src:app.imagesPiccolo.stanceUp},
	 {id: "piccoloStanceDown", src:app.imagesPiccolo.stanceDown},
	 {id: "piccoloHit1", src:app.imagesPiccolo.hit1},
	 {id: "piccoloHit2", src:app.imagesPiccolo.hit2},
     {id: "piccoloSlowFly", src:app.imagesPiccolo.slowFly},
     {id: "piccoloFastFly", src:app.imagesPiccolo.fastFly},
	 {id: "piccoloFlyUp", src:app.imagesPiccolo.flyUp},
	 {id: "piccoloFlyUpUp", src:app.imagesPiccolo.flyUpUp},
	 {id: "piccoloFlyUpDown", src:app.imagesPiccolo.flyUpDown},
	 {id: "piccoloFlyDownSlow", src:app.imagesPiccolo.flyDownSlow},
	 {id: "piccoloFlyDownFast", src:app.imagesPiccolo.flyDownFast},
	 {id: "piccoloFallKick", src:app.imagesPiccolo.fallKick},
	 {id: "piccoloReverse", src:app.imagesPiccolo.reverse},
	 {id: "piccoloPunch", src:app.imagesPiccolo.punch},
	 {id: "piccoloKneePrep", src:app.imagesPiccolo.kneePrep},
	 {id: "piccoloKnee", src:app.imagesPiccolo.knee},
	 {id: "piccoloPunchPrep", src:app.imagesPiccolo.punchPrep},
	 {id: "piccoloHardKick", src:app.imagesPiccolo.hardKick},
	 {id: "piccoloGround", src:app.imagesPiccolo.ground},
	 {id: "piccoloFallSide", src:app.imagesPiccolo.fallSide},
	 {id: "piccoloHardKickPrep", src:app.imagesPiccolo.hardKickPrep},
	 {id: "piccoloHardKickSwing", src:app.imagesPiccolo.hardKickSwing},
	 {id: "piccoloHardPunch", src:app.imagesPiccolo.hardPunch},
	 {id: "piccoloHardPunchAir", src:app.imagesPiccolo.hardPunchAir},
	 {id: "piccoloHardPunchAirPrep", src:app.imagesPiccolo.hardPunchAirPrep},
	 {id: "piccoloHardPunchAirSwing", src:app.imagesPiccolo.hardPunchAirSwing},
	 {id: "piccoloHardPunchPrep", src:app.imagesPiccolo.hardPunchPrep},
	 {id: "piccoloHitHard", src:app.imagesPiccolo.hitHard},
	 {id: "piccoloInjured", src:app.imagesPiccolo.injured},
	 {id: "piccoloKick", src:app.imagesPiccolo.kick},
	 {id: "piccoloKickPrep", src:app.imagesPiccolo.kickPrep},
	 {id: "piccoloBlastPrep", src:app.imagesPiccolo.blastPrep},
	 {id: "piccoloBlastPrepAir", src:app.imagesPiccolo.blastPrepAir},
	 {id: "piccoloBlast", src:app.imagesPiccolo.blast},
	 {id: "piccoloBlastAir", src:app.imagesPiccolo.blastAir},
	 {id: "piccoloBlock", src:app.imagesPiccolo.block},
	 {id: "piccoloFallDown", src:app.imagesPiccolo.fallDown},
	 {id: "piccoloTaunt", src:app.imagesPiccolo.taunt},
	 {id: "piccololaunchPrep", src:app.imagesPiccolo.launchPrep},
	 {id: "piccololaunchSwing", src:app.imagesPiccolo.launchSwing},
	 {id: "piccololaunch", src:app.imagesPiccolo.launch},
	 {id: "piccoloPose1", src:app.imagesPiccolo.pose1},
	 {id: "piccoloPose2", src:app.imagesPiccolo.pose2},
	 {id: "piccoloPose3", src:app.imagesPiccolo.pose3},
	 {id: "piccoloPose4", src:app.imagesPiccolo.pose4},
	 {id: "piccoloEnergy1", src:app.imagesPiccolo.energy1},
	 {id: "piccoloEnergy2", src:app.imagesPiccolo.energy2},
	 {id: "piccoloEnergy3", src:app.imagesPiccolo.energy3},
	 {id: "piccoloEnergy4", src:app.imagesPiccolo.energy4},
	 {id: "piccoloCharge", src:app.imagesPiccolo.charge},
	 {id: "piccoloBeamPrep", src:app.imagesPiccolo.beamPrep},
	 {id: "piccoloBeam", src:app.imagesPiccolo.beam}, 
	 {id: "piccoloBlast2", src:app.imagesPiccolo.blast2},
	 
	 //Gohan LOADING
	 {id: "gohanStance", src:app.imagesGohan.stance},
	 {id: "gohanStanceUp", src:app.imagesGohan.stanceUp},
	 {id: "gohanStanceDown", src:app.imagesGohan.stanceDown},
	 {id: "gohanBeam", src:app.imagesGohan.beam},
	 {id: "gohanBeamUp", src:app.imagesGohan.beamUp},
	 {id: "gohanBeamDown", src:app.imagesGohan.beamDown},
	 {id: "gohanBeamPrep", src:app.imagesGohan.beamPrep},
	 {id: "gohanHit1", src:app.imagesGohan.hit1},
     {id: "gohanSlowFly", src:app.imagesGohan.slowFly},
     {id: "gohanFastFly", src:app.imagesGohan.fastFly},
	 {id: "gohanFlyUp", src:app.imagesGohan.flyUp},
	 {id: "gohanFlyUpUp", src:app.imagesGohan.flyUpUp},
	 {id: "gohanFlyUpDown", src:app.imagesGohan.flyUpDown},
	 {id: "gohanFlyDownSlow", src:app.imagesGohan.flyDownSlow},
	 {id: "gohanFlyDownFast", src:app.imagesGohan.flyDownFast},
	 {id: "gohanReverse", src:app.imagesGohan.reverse},
	 {id: "gohanLeftPunch", src:app.imagesGohan.leftPunch},
	 {id: "gohanRightPunch", src:app.imagesGohan.rightPunch},
	 {id: "gohanPunchPrep", src:app.imagesGohan.punchPrep},
	 {id: "gohanHardKick", src:app.imagesGohan.hardKick},
	 {id: "gohanFallKick", src:app.imagesGohan.fallKick},
	 {id: "gohanGround", src:app.imagesGohan.ground},
	 {id: "gohanGround2", src:app.imagesGohan.ground2},
	 {id: "gohanFallSide", src:app.imagesGohan.fallSide},
	 {id: "gohanHardKickPrep", src:app.imagesGohan.hardKickPrep},
	 {id: "gohanHardKickSwing", src:app.imagesGohan.hardKickSwing},
	 {id: "gohanHardPunchSwing", src:app.imagesGohan.hardPunchSwing},
	 {id: "gohanHardPunchSwing2", src:app.imagesGohan.hardPunchSwing2},
	 {id: "gohanHardPunchAir", src:app.imagesGohan.hardPunchAir},
	 {id: "gohanHardPunchAirPrep", src:app.imagesGohan.hardPunchAirPrep},
	 {id: "gohanHardPunchAirSwing", src:app.imagesGohan.hardPunchAirSwing},
	 {id: "gohanHardPunchPrep", src:app.imagesGohan.hardPunchPrep},
	 {id: "gohanHitHard", src:app.imagesGohan.hitHard},
	 {id: "gohanInjured", src:app.imagesGohan.injured},
	 {id: "gohanKick", src:app.imagesGohan.kick},
	 {id: "gohanKickPrep", src:app.imagesGohan.kickPrep},
	 {id: "gohanBlastPrep", src:app.imagesGohan.blastPrep},
	 {id: "gohanBlast", src:app.imagesGohan.blast},
	 {id: "gohanHeadPrep", src:app.imagesGohan.headPrep},
	 {id: "gohanHead", src:app.imagesGohan.head},
	 {id: "gohanBlock", src:app.imagesGohan.block},
	 {id: "gohanFallDown", src:app.imagesGohan.fallDown},
	 {id: "gohanTaunt", src:app.imagesGohan.taunt},
	 {id: "gohanlaunchPrep", src:app.imagesGohan.launchPrep},
	 {id: "gohanlaunchSwing", src:app.imagesGohan.launchSwing},
	 {id: "gohanlaunch", src:app.imagesGohan.launch},
	 {id: "gohanCharge", src:app.imagesGohan.charge},
	 {id: "gohanSevere", src:app.imagesGohan.gohanSevere},
	 {id: "gohanSevere2", src:app.imagesGohan.gohanSevere2},
	 {id: "gohanMad1", src:app.imagesGohan.mad1},
	 {id: "gohanSS2", src:app.imagesGohan.ss2},
	 {id: "gohanAura1", src:app.imagesGohan.aura1},
	 {id: "gohanAura2", src:app.imagesGohan.aura2},
	 {id: "gohanAura3", src:app.imagesGohan.aura3},
	 {id: "gohanAura4", src:app.imagesGohan.aura4},
	 {id: "gohanAura5", src:app.imagesGohan.aura5},
	 
	 
	 //Tien LOADING
	 {id: "tienStance", src:app.imagesTien.stance},
	 {id: "tienStanceUp", src:app.imagesTien.stanceUp},
	 {id: "tienStanceDown", src:app.imagesTien.stanceDown},
	 {id: "tienHit1", src:app.imagesTien.hit1},
     {id: "tienSlowFly", src:app.imagesTien.slowFly},
     {id: "tienFastFly", src:app.imagesTien.fastFly},
	 {id: "tienFlyUp", src:app.imagesTien.flyUp},
	 {id: "tienFlyUpUp", src:app.imagesTien.flyUpUp},
	 {id: "tienFlyUpDown", src:app.imagesTien.flyUpDown},
	 {id: "tienFlyDownSlow", src:app.imagesTien.flyDownSlow},
	 {id: "tienFlyDownFast", src:app.imagesTien.flyDownFast},
	 {id: "tienReverse", src:app.imagesTien.reverse},
	 {id: "tienGround", src:app.imagesTien.ground},
	 {id: "tienGround2", src:app.imagesTien.ground2},
	 {id: "tienFallSide", src:app.imagesTien.fallSide},
	 {id: "tienHitHard", src:app.imagesTien.hitHard},
	 {id: "tienInjured", src:app.imagesTien.injured},
	 {id: "tienFallDown", src:app.imagesTien.fallDown},
	 {id: "tienTaunt", src:app.imagesTien.taunt},
	 {id: "tienSolar", src:app.imagesTien.solar},
	 {id: "tienTriBeam1", src:app.imagesTien.triBeam1},
	 {id: "tienTriBeam2", src:app.imagesTien.triBeam2},
	 {id: "tienTriBeam3", src:app.imagesTien.triBeam3},
	 {id: "tienTriBeam4", src:app.imagesTien.triBeam4},
	 {id: "tienTriBeam5", src:app.imagesTien.triBeam5},
	 {id: "tienMad1", src:app.imagesTien.mad1},
	 
	  //Krillin LOADING
	 {id: "krillinStance", src:app.imagesKrillin.stance},
	 {id: "krillinStanceUp", src:app.imagesKrillin.stanceUp},
	 {id: "krillinStanceDown", src:app.imagesKrillin.stanceDown},
	 {id: "krillinHit1", src:app.imagesKrillin.hit1},
     {id: "krillinSlowFly", src:app.imagesKrillin.slowFly},
     {id: "krillinFastFly", src:app.imagesKrillin.fastFly},
	 {id: "krillinFlyUp", src:app.imagesKrillin.flyUp},
	 {id: "krillinFlyUpUp", src:app.imagesKrillin.flyUpUp},
	 {id: "krillinFlyUpDown", src:app.imagesKrillin.flyUpDown},
	 {id: "krillinFlyDownSlow", src:app.imagesKrillin.flyDownSlow},
	 {id: "krillinFlyDownFast", src:app.imagesKrillin.flyDownFast},
	 {id: "krillinReverse", src:app.imagesKrillin.reverse},
	 {id: "krillinGround", src:app.imagesKrillin.ground},
	 {id: "krillinGround2", src:app.imagesKrillin.ground2},
	 {id: "krillinFallSide", src:app.imagesKrillin.fallSide},
	 {id: "krillinHitHard", src:app.imagesKrillin.hitHard},
	 {id: "krillinInjured", src:app.imagesKrillin.injured},
	 {id: "krillinFallDown", src:app.imagesKrillin.fallDown},
	 {id: "krillinTaunt", src:app.imagesKrillin.taunt},
	 {id: "krillinSolar", src:app.imagesKrillin.solar},
	 {id: "krillinDisk1", src:app.imagesKrillin.disk1},
	 {id: "krillinDisk2", src:app.imagesKrillin.disk2},
	 {id: "krillinDisk3", src:app.imagesKrillin.disk3},
	 {id: "krillinDisk4", src:app.imagesKrillin.disk4},
	 {id: "krillinMad1", src:app.imagesKrillin.mad1},
	 {id: "krillinMad2", src:app.imagesKrillin.mad2},
	 
	 //Android 16 LOADING
     {id: "16Stance", src:app.images16.stance},
	 {id: "16Stance2", src:app.images16.stance2},
	 
	 //Attack LOADING
	 {id: "tele", src:app.attack.tele},
	 {id: "tele2", src:app.attack.tele2},
	 {id: "tele3", src:app.attack.tele3},
	 {id: "tele4", src:app.attack.tele4},
	 {id: "tele5", src:app.attack.tele5},
	 {id: "tele6", src:app.attack.tele6},
	 {id: "teleThin", src:app.attack.teleThin},
	 {id: "tele2Thin", src:app.attack.tele2Thin},
	 {id: "tele3Thin", src:app.attack.tele3Thin},
	 {id: "tele4Thin", src:app.attack.tele4Thin},
	 {id: "blast1", src:app.attack.blast1},
	 {id: "explosion1", src:app.attack.explosion1},
	 {id: "explosion2", src:app.attack.explosion2},
	 {id: "explosion3", src:app.attack.explosion3},
	 {id: "explosion4", src:app.attack.explosion4},
	 {id: "explosion5", src:app.attack.explosion5},
	 {id: "explosion6", src:app.attack.explosion6},
	 {id: "bigExplosion1", src:app.attack.bigExplosion1},
	 {id: "bigExplosion2", src:app.attack.bigExplosion2},
	 {id: "bigExplosion3", src:app.attack.bigExplosion3},
	 {id: "bigExplosion4", src:app.attack.bigExplosion4},
	 {id: "bigExplosion5", src:app.attack.bigExplosion5},
	 {id: "bigExplosion6", src:app.attack.bigExplosion6}, 
	 {id: "circleExplosion2", src:app.attack.circleExplosion2},
	 {id: "circleExplosion3", src:app.attack.circleExplosion3},
	 {id: "circleExplosion4", src:app.attack.circleExplosion4},
	 {id: "circleExplosion5", src:app.attack.circleExplosion5},
	 {id: "circleExplosion6", src:app.attack.circleExplosion6},
	 {id: "circleExplosionB2", src:app.attack.circleExplosionB2},
	 {id: "circleExplosionB3", src:app.attack.circleExplosionB3},
	 {id: "circleExplosionB4", src:app.attack.circleExplosionB4},
	 {id: "circleExplosionB5", src:app.attack.circleExplosionB5},
	 {id: "circleExplosionB6", src:app.attack.circleExplosionB6},
	 {id: "auraWhite1", src:app.attack.auraWhite1},
	 {id: "auraWhite2", src:app.attack.auraWhite2},
	 {id: "auraWhite3", src:app.attack.auraWhite3},
	 {id: "auraWhite4", src:app.attack.auraWhite4},
	 {id: "auraYellow1", src:app.attack.auraYellow1},
	 {id: "auraYellow2", src:app.attack.auraYellow2},
	 {id: "auraYellow3", src:app.attack.auraYellow3},
	 {id: "auraYellow4", src:app.attack.auraYellow4},
	 {id: "beam1", src:app.attack.beam1},
	 {id: "beam2", src:app.attack.beam2},
	 {id: "beam3", src:app.attack.beam3},
	 {id: "beam4", src:app.attack.beam4},
	 {id: "beam5", src:app.attack.beam5},
	 {id: "ball1", src:app.attack.ball1},
	 {id: "ball2", src:app.attack.ball2},
	 {id: "beamB1", src:app.attack.beamB1},
	 {id: "beamB2", src:app.attack.beamB2},
	 {id: "beamB3", src:app.attack.beamB3},
	 {id: "beamB4", src:app.attack.beamB4},
	 {id: "beamB5", src:app.attack.beamB5},
	 {id: "blastCharge1", src:app.attack.blastCharge1},
	 {id: "beamT1", src:app.attack.beamT1},
	 {id: "triBeam", src:app.attack.triBeam},
	 {id: "disk1", src:app.attack.disk1},
	 {id: "disk2", src:app.attack.disk2},
	 {id: "sparks1", src:app.attack.sparks1},
	 {id: "sparks2", src:app.attack.sparks2},
	 {id: "sparks3", src:app.attack.sparks3},
	 {id: "sparks4", src:app.attack.sparks4},
	 {id: "burst1", src:app.attack.burst1},
	 {id: "burst2", src:app.attack.burst2},
	 {id: "burst3", src:app.attack.burst3},
	 {id: "burst4", src:app.attack.burst4},
	 {id: "field1", src:app.attack.field1},
	 {id: "field2", src:app.attack.field2},
	 {id: "field3", src:app.attack.field3},
	 {id: "field4", src:app.attack.field4},
	 {id: "field5", src:app.attack.field5},
	 {id: "field6", src:app.attack.field6},
	 {id: "field7", src:app.attack.field7},
	 {id: "field8", src:app.attack.field8},
	 {id: "fieldMain", src:app.attack.fieldMain},
	 {id: "nuke1", src:app.attack.nuke1},
	 {id: "nuke2", src:app.attack.nuke2},
	 {id: "nuke3", src:app.attack.nuke3},
	 {id: "nuke4", src:app.attack.nuke4},
	 {id: "nuke5", src:app.attack.nuke5},
	 {id: "nuke6", src:app.attack.nuke6},
	 {id: "PB1", src:app.attack.PB1},
	 {id: "PB2", src:app.attack.PB2},
	 {id: "PB3", src:app.attack.PB3},
	 {id: "PB4", src:app.attack.PB4},
	 {id: "PB5", src:app.attack.PB5},
	 {id: "PB6", src:app.attack.PB6},
	 {id: "PBC1", src:app.attack.PBC1},
	 {id: "PBC2", src:app.attack.PBC2},
	 {id: "PBC3", src:app.attack.PBC3},
	 {id: "PBC4", src:app.attack.PBC4},
	 {id: "PBC5", src:app.attack.PBC5},
	 {id: "PBC6", src:app.attack.PBC6},
	]);
	
}

